# Configuración de Nixpacks para Power GYMA
# Este archivo es opcional pero proporciona mejor control sobre el proceso de build

[variables]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["nodejs_18", "nodePackages.npm", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan storage:link"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
