# Configuración de Nixpacks para Power GYMA - Railway
# Optimizado para producción

[variables]
NODE_VERSION = "20.19.0"
PHP_VERSION = "8.2"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "mkdir -p storage/framework/sessions",
  "mkdir -p storage/framework/views",
  "mkdir -p storage/framework/cache",
  "mkdir -p storage/logs",
  "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --class=GeographicDataSeeder --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
