# Configuración de Nixpacks para Power GYMA - SIMPLIFICADA
# Railway deployment configuration

[variables]
NODE_VERSION = "20"
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "php artisan config:clear",
  "php artisan cache:clear"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --class=GeographicDataSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT"
